"""Global constants for the research agent application."""

# Embedding dimensions
EMBEDDING_DIMENSIONS = 1536  # OpenAI text-embedding-3-small

# Database connection pool settings
DEFAULT_DB_POOL_SIZE = 5
DEFAULT_DB_MAX_OVERFLOW = 10
DEFAULT_DB_POOL_TIMEOUT = 30  # seconds
DEFAULT_DB_POOL_RECYCLE = 3600  # 1 hour

# Cache settings
DEFAULT_CACHE_POOL_SIZE = 10
DEFAULT_CACHE_SOCKET_TIMEOUT = 5  # seconds
DEFAULT_CACHE_DEFAULT_TTL = 3600  # 1 hour

# LLM settings
DEFAULT_LLM_TEMPERATURE = 0.7
DEFAULT_LLM_MAX_TOKENS = 4096
DEFAULT_LLM_TIMEOUT = 120  # seconds

# Circuit breaker settings
DEFAULT_CIRCUIT_FAILURE_THRESHOLD = 3
DEFAULT_CIRCUIT_TIMEOUT = 60  # seconds
DEFAULT_CIRCUIT_SUCCESS_THRESHOLD = 2

# Retry settings
DEFAULT_RETRY_MAX_ATTEMPTS = 3
DEFAULT_RETRY_BACKOFF_FACTOR = 2.0
DEFAULT_RETRY_BACKOFF_BASE = 1.0  # seconds
DEFAULT_RETRY_MAX_BACKOFF = 60.0  # seconds
DEFAULT_RETRY_JITTER_PERCENT = 0.25

# Messaging settings
DEFAULT_RABBITMQ_PORT = 5672
DEFAULT_RABBITMQ_HEARTBEAT = 60  # seconds
DEFAULT_RABBITMQ_CONNECTION_TIMEOUT = 30  # seconds
DEFAULT_RABBITMQ_PREFETCH_COUNT = 10

# Vector search settings
DEFAULT_SIMILARITY_THRESHOLD = 0.85
DEFAULT_VECTOR_SEARCH_LIMIT = 10

# Digest settings
DEFAULT_DIGEST_ITEMS_COUNT = 15
MIN_DIGEST_ITEMS_COUNT = 5
MAX_DIGEST_ITEMS_COUNT = 50

# Logging
MAX_LOG_STRING_LENGTH = 1000
MAX_ERROR_MESSAGE_LENGTH = 500
MAX_ERROR_SNIPPET_LENGTH = 500
MAX_CACHE_KEY_LENGTH = 50

# Rate limiting
DEFAULT_RATE_LIMIT_REQUESTS = 100
DEFAULT_RATE_LIMIT_PERIOD = 60  # seconds

# API timeouts
DEFAULT_API_TIMEOUT = 30  # seconds
DEFAULT_HEALTH_CHECK_TIMEOUT = 5  # seconds
